# db.py
import oracledb

try:
    conn = oracledb.connect(
        user="RM568480",
        password="030800",
        dsn="oracle.fiap.com.br:1521/ORCL"
    )
    cursor = conn.cursor()
    conexao = True
except Exception as e:
    print("Erro ao conectar no banco:", e)
    conexao = False

if conexao:
    try:
        cursor.execute("""
            CREATE TABLE USUARIOS (
                EMAIL VARCHAR2(200) PRIMARY KEY,
                SENHA VARCHAR2(200),
                SEXO VARCHAR2(20),
                DATA_NASCIMENTO DATE,
                CARGO VARCHAR2(200),
                CREATED_AT DATE
            )
        """)
    except:
        pass  # tabela já existe

    try:
        cursor.execute("""
            CREATE TABLE DIARIOS (
                ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                EMAIL VARCHAR2(200),
                DATA_REG DATE,
                HUMOR VARCHAR2(50),
                FOCO_HORAS NUMBER,
                SOBRECARGA NUMBER(1),
                DORMIU_BEM NUMBER(1),
                ENERGIA NUMBER,
                ESTRESSE NUMBER,
                CREATED_AT DATE
            )
        """)
    except:
        pass

    try:
        cursor.execute("""
            CREATE TABLE METRICAS_USUARIO (
                ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                EMAIL VARCHAR2(200),
                DATA_REG DATE,
                VELOCIDADE_DIGITACAO NUMBER,
                TEMPO_PAUSA NUMBER,
                TEMPO_TELA_LIGADA NUMBER,
                TEMPO_INTERACAO NUMBER,
                TEMPO_MOUSE NUMBER,
                CREATED_AT DATE
            )
        """)

    except:
        pass